# Generated by Django 2.0 on 2020-06-12 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('psw', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercice',
            name='exo_file',
            field=models.ImageField(upload_to=''),
        ),
    ]
