# Generated by Django 2.1 on 2020-09-10 09:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('psw', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Corrections',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('course_file', models.ImageField(blank=True, null=True, upload_to='media')),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='HistoricalCorrections',
            fields=[
                ('id', models.IntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('created_at', models.DateTimeField(blank=True, editable=False)),
                ('updated_at', models.DateTimeField(blank=True, editable=False)),
                ('course_file', models.TextField(blank=True, max_length=100, null=True)),
                ('description', models.TextField(blank=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
            ],
            options={
                'verbose_name': 'historical corrections',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.RenameModel(
            old_name='HistoricalExercice',
            new_name='HistoricalExercices',
        ),
        migrations.AlterModelOptions(
            name='historicalexercices',
            options={'get_latest_by': 'history_date', 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical exercices'},
        ),
        migrations.RenameField(
            model_name='courses',
            old_name='Course_file',
            new_name='course_file',
        ),
        migrations.RenameField(
            model_name='historicalcourses',
            old_name='Course_file',
            new_name='course_file',
        ),
        migrations.RenameModel(
            old_name='Exercice',
            new_name='Exercices',
        ),
        migrations.AddField(
            model_name='historicalcorrections',
            name='exercice',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='psw.Exercices'),
        ),
        migrations.AddField(
            model_name='historicalcorrections',
            name='history_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='corrections',
            name='exercice',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='psw.Exercices'),
        ),
    ]
