# Generated by Django 2.0 on 2020-08-13 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('psw', '0003_auto_20200612_1557'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercice',
            name='exo_file',
            field=models.FileField(upload_to='media'),
        ),
    ]
