# Generated by Django 3.1 on 2020-08-13 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('psw', '0005_exercice_niveau'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercice',
            name='exo_file',
            field=models.FileField(blank=True, null=True, upload_to='media'),
        ),
    ]
