# Generated by Django 2.0 on 2020-09-05 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('psw', '0005_historicalexercice'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercice',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='historicalexercice',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
