# Generated by Django 2.0 on 2020-09-05 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('psw', '0006_auto_20200905_1351'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercice',
            name='exo_file',
            field=models.ImageField(blank=True, null=True, upload_to='media'),
        ),
        migrations.AlterField(
            model_name='exercice',
            name='niveau',
            field=models.CharField(choices=[(1, 'Sixieme College'), (2, 'Cinquieme College'), (4, 'Quatrieme College'), (5, 'troisieme College'), (6, 'Seconde Lycee'), (7, 'Premiere Lycee'), (0, 'Terminale Lycee')], default=0, max_length=6),
        ),
        migrations.AlterField(
            model_name='historicalexercice',
            name='niveau',
            field=models.CharField(choices=[(1, 'Sixieme College'), (2, 'Cinquieme College'), (4, 'Quatrieme College'), (5, 'troisieme College'), (6, 'Seconde Lycee'), (7, 'Premiere Lycee'), (0, 'Terminale Lycee')], default=0, max_length=6),
        ),
    ]
